services:
  # Docker Sql Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: zone_vitae_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./data/datos.sql:/docker-entrypoint-initdb.d/init.sql
      - sqlserver_data:/var/opt/mssql
    networks:
      - zonevitae_dev_network

networks:
  zonevitae_dev_network:
    driver: bridge
