services:
  # Docker Sql Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - zonevitae_dev_network
    restart: unless-stopped
  # Docker .Net Core Web API

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORT=8081
    ports:
      - '8080:8080'
      - '8081:8081'
    build:
      context: .

networks:
  zonevitae_dev_network:
    driver: bridge
